version: "3.8" # ← これがないと gpus: all は無効になります

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.nvidia
    gpus: all
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - ./project:/project
    ports:
      - "9000:9000"
      - "8000:8000"
    restart: "no"
    tty: true
